### ISSUE TITLE
Dynamically compute IPV4 Prefixes

### ISSUE THREAD

**Issue by arunk054** [mnuzen/step-capstone-2020#38]
Group IPs into each of the three buckets /24, /16, /8 or classes C, B, A. A brute force way would be to simply extract the three prefixes for each unique IP in the PCAP file. And aggregate prefixes that are same.

This is probably covered in #30  but we should just focus on the problem of masking IPs on that issue.

**Comment by mnuzen** [comment]
Prior to grouping IPs into buckets, we condense the IP addresses by first byte, otherwise there's no way to see all packet data for larger files. Condensing means max number of nodes in our visualization is 255. See #50.

> before: over 10k connections for visualization to parse

![Screenshot 2020-08-11 at 12 20 04 PM](https://user-images.githubusercontent.com/43756178/89946673-2184ed80-dbd8-11ea-9579-e19890950624.png)

> after: max 255 connections for visualization to parse

![Screenshot 2020-08-11 at 12 34 01 PM](https://user-images.githubusercontent.com/43756178/89946668-2053c080-dbd8-11ea-82d6-a3beef24804f.png)

**Comment by mnuzen** [comment]
Added two visualizations -- one for distribution of protocols over IP classes and one for distribution of IP addresses based on prefixes):

![Screenshot 2020-08-11 at 10 12 04 PM](https://user-images.githubusercontent.com/43756178/90474674-af7e3e00-e0da-11ea-9cb5-72abc6eb9645.png)

![Screenshot 2020-08-17 at 10 13 45 PM](https://user-images.githubusercontent.com/43756178/90474680-b311c500-e0da-11ea-83fc-4d31ece94476.png)
