### ISSUE TITLE
Implement reverse IP lookup

### ISSUE THREAD

**Issue by Erik-Handeland** [mnuzen/step-capstone-2020#7]
add reverse IP lookup to populate Domain and Location section of database

**Comment by thorncorona** [comment]
I already implemented location lookup. Just call the GeolocationDAO when we put things together.

**Comment by arunk054** [comment]
Can we commit the reverse location lookup as a separate module. It does not have to be a DAO at this point since I assume you are directly talking to an external service and getting the output.
It could be something like:
```
public interface ReverseIPLookup {
  String getLookup(String ip);
}
```
Jevin can provide a class that implements this Interface, for now it can be simple like this
public class ExternalReverseIPLookup implements Rever.. .{
// Initialize connection to ext service etc
// implement the interface method.
}

**Comment by thorncorona** [comment]
Added in #9. Will work on adding in DNS lookup.

**Comment by thorncorona** [comment]
DNS lookup in #17 and #19
